import Video2 from "./b.mp4"
const Videos = [{
        id: "1",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        // link: Video2,
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "What is JavaScript ?",
        pagename: "programming with Mosh",
        view: "1M",
        time: "1 year",
    },
    {
        id: "2",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "3",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "4",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "5",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "6",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "7",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "8",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "9",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "10",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "11",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "12",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "13",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "14",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "15",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
    {
        id: "16",
        video_link: Video2,
        link: "https://s1.1zoom.me/big3/718/Logo_Emblem_Youtube_Red_background_529384_1920x1080.jpg",
        pagepic: "https://static.wikia.nocookie.net/youtube/images/4/43/Programming_with_Mosh.jpg",
        title: "title",
        pagename: "page name",
        view: "no",
        time: "time",
    },
];

export default Videos